version: '3.8'

services:
  mikrotik-controller:
    image: ispacademy/mikrotik-controller:latest
    container_name: mikrotik-controller
    ports:
      - "3333:3333"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3333"]
      interval: 30s
      timeout: 10s
      retries: 3