#!/bin/bash

echo "🚀 Guardian Relay v1.3.0 - Deployment Commands"
echo "============================================"
echo ""
echo "1. GIT COMMANDS - Commit and Push to GitHub:"
echo "---------------------------------------------"
echo "git add -A"
echo "git commit -m \"Release Guardian Relay v1.3.0 - Queue Pagination and IP Blocking"
echo ""
echo "- Add pagination for queue management (10 items per page)"
echo "- Add 'Show All Queues' button for viewing all queues"
echo "- Add BLOCK/UNBLOCK functionality for DHCP leases"
echo "- Integrate with BLOCKED-CUSTOMERS firewall address list"
echo "- Use router local time for block comments"
echo "- Update version to 1.3.0 across all files\""
echo ""
echo "git tag -a v1.3.0 -m \"Release v1.3.0 - Queue Pagination and IP Blocking\""
echo "git push origin main"
echo "git push origin v1.3.0"
echo ""
echo "2. DOCKER COMMANDS - Build and Push Docker Image:"
echo "--------------------------------------------------"
echo "# Build the Docker image"
echo "docker build -t guardian-relay:1.3.0 ."
echo "docker build -t guardian-relay:latest ."
echo ""
echo "# Tag for Docker Hub (replace 'yourusername' with your Docker Hub username)"
echo "docker tag guardian-relay:1.3.0 yourusername/guardian-relay:1.3.0"
echo "docker tag guardian-relay:1.3.0 yourusername/guardian-relay:latest"
echo ""
echo "# Push to Docker Hub"
echo "docker push yourusername/guardian-relay:1.3.0"
echo "docker push yourusername/guardian-relay:latest"
echo ""
echo "3. GITHUB RELEASE - Create Release on GitHub:"
echo "---------------------------------------------"
echo "# Using GitHub CLI (gh)"
echo "gh release create v1.3.0 \\"
echo "  --title \"Guardian Relay v1.3.0 - Queue Pagination and IP Blocking\" \\"
echo "  --notes-file RELEASE_NOTES_v1.3.0.md \\"
echo "  --draft"
echo ""
echo "# Or manually:"
echo "1. Go to https://github.com/yourusername/guardian-relay/releases/new"
echo "2. Tag: v1.3.0"
echo "3. Title: Guardian Relay v1.3.0 - Queue Pagination and IP Blocking"
echo "4. Copy contents from RELEASE_NOTES_v1.3.0.md"
echo "5. Publish release"
echo ""
echo "4. OPTIONAL - Update Docker Compose Examples:"
echo "---------------------------------------------"
echo "# In your documentation or examples repo:"
echo "# Update docker-compose.yml to use the new version"
echo "sed -i 's/guardian-relay:.*$/guardian-relay:1.3.0/' docker-compose.yml"
echo ""
echo "============================================"
echo "📋 Pre-flight Checklist:"
echo "- [ ] Server is stopped (current PID: $(ps aux | grep 'node src/server.js' | grep -v grep | awk '{print $2}'))"
echo "- [ ] All changes are saved"
echo "- [ ] Tests have been run"
echo "- [ ] Documentation is updated"
echo ""
echo "🎯 Quick Copy-Paste Commands:"
echo "------------------------------"
echo "git add -A && git commit -m \"Release Guardian Relay v1.3.0\" && git tag -a v1.3.0 -m \"Release v1.3.0\" && git push origin main && git push origin v1.3.0"